User-can-delete-an-entry-Bishan-Webeshete
BishanWebeshete/code-journal pull request #8
Opened 2023-02-18 22:14 UTC by BishanWebeshete

![Kapture 2023-02-18 at 14 13 34](https://user-images.githubusercontent.com/121692569/219901637-906c18c1-7248-4418-81c1-665aa3b74819.gif)

2023-02-20 16:17 UTC, shawnkost requested changes
Couple changes requested here Bishan!

2023-02-20 16:17 UTC, shawnkost commented on css/styles.css
> +    padding-left: 35.5rem;
You should avoid using such large rem values, you should really only be going up to about `5rem`. If you have such large values, then you're probably doing something "hacky" to get this to work

2023-02-20 16:17 UTC, shawnkost commented on js/main.js
> +      data.nextEntryId--;
You shouldn't be decreasing `nextEntryId`, you only want this value to stay the same, or to increase

2023-02-21 03:02 UTC, BishanWebeshete commented
![Kapture 2023-02-20 at 19 02 25](https://user-images.githubusercontent.com/121692569/220236929-c3739732-98b2-4408-bc5f-10de1ca239d2.gif)

2023-02-21 22:56 UTC, shawnkost approved these changes
👍🏻

2023-02-22 03:58 UTC, merged